services:
  - type: web
    name: onewill-website
    env: static
    buildCommand: true
    staticPublishPath: ./
    headers:
      # デバッグ用ヘッダー
      - path: /*
        name: X-Debug-Mode
        value: "true"
      - path: /*
        name: X-Host-Provider
        value: "Render"
      - path: /*
        name: X-CSP-Nonce
        value: "oneWill2024"
      # Content Security Policy
      - path: /*
        name: Content-Security-Policy
        value: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' 'nonce-oneWill2024' https://code.jquery.com https://unpkg.com https://cdnjs.cloudflare.com https://cdn.jsdelivr.net https://www.clarity.ms https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://unpkg.com https://cdn.jsdelivr.net; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://www.clarity.ms https://www.google-analytics.com;"
      # キャッシュ設定
      - path: /*
        name: Cache-Control
        value: "public, max-age=86400"
      - path: /*.html
        name: Cache-Control
        value: "public, max-age=3600"
      - path: /*.css
        name: Cache-Control
        value: "public, max-age=3600"
      - path: /*.js
        name: Cache-Control
        value: "public, max-age=3600"
      - path: /*.js
        name: Content-Type
        value: "application/javascript; charset=utf-8"
      - path: /*.js
        name: X-JS-Loaded
        value: "true"
      - path: /*.jpg
        name: Cache-Control
        value: "public, max-age=604800"
      - path: /*.png
        name: Cache-Control
        value: "public, max-age=604800"
      - path: /*.ico
        name: Cache-Control
        value: "public, max-age=604800"
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      # セキュリティヘッダー
      - path: /*
        name: X-Content-Type-Options
        value: "nosniff"
      - path: /*
        name: X-XSS-Protection
        value: "1; mode=block"
      - path: /*
        name: X-Frame-Options
        value: "SAMEORIGIN"
      - path: /*
        name: Referrer-Policy
        value: "strict-origin-when-cross-origin"
    routes:
      - type: rewrite
        source: /(.*)
        destination: /$1.html
        condition: "!PathExists(/{1}) && PathExists(/{1}.html)"
    envVars:
      - key: APACHE_MODULES
        value: rewrite headers deflate
      - key: DEBUG_MODE
        value: "true"
