services:
  - type: web
    name: tokutei-ginou-pro
    env: static
    buildCommand: echo "Static site"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /css/*
        name: Cache-Control
        value: max-age=31536000
      - path: /js/*
        name: Cache-Control
        value: max-age=31536000
      - path: /public/image/*
        name: Cache-Control
        value: max-age=31536000
      - path: /fonts/*
        name: Cache-Control
        value: max-age=31536000
    envVars:
      - key: APACHE_MODULES
        value: rewrite headers
